CREATE TABLE knowledge_article (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    category varchar(64) NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('portuguese', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('portuguese', coalesce(content, '')), 'B')
    ) STORED,
    CONSTRAINT ck_knowledge_article_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_knowledge_article_content_not_blank CHECK (length(btrim(content)) > 0),
    CONSTRAINT ck_knowledge_article_category CHECK (
        category IN (
            'FIBRA_ONU',
            'WIFI',
            'DNS_IPV6',
            'CGNAT_NAT',
            'LATENCIA_PERDA_PACOTES',
            'ROTEADORES_CONFIGURACOES',
            'DIAGNOSTICO_CONECTIVIDADE'
        )
    )
);

CREATE INDEX idx_knowledge_article_search_vector
    ON knowledge_article USING gin (search_vector);

CREATE FUNCTION set_knowledge_article_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_knowledge_article_updated_at
    BEFORE UPDATE ON knowledge_article
    FOR EACH ROW
    EXECUTE FUNCTION set_knowledge_article_updated_at();
